export { default as Nav } from './Nav'
export { default as Contact } from './Contact'
export { default as Project } from './Project'
export { default as Header } from './Header'
export { default as PersonalWork } from './PersonalWork'
export { default as ProfessionalWork } from './ProfessionalWork'